spring.datasource.url=jdbc:postgresql://localhost:5432/ArtVistaDB
spring.datasource.username=postgres
spring.datasource.password=RG123
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
# Server port (optional)
server.port=8080

# Multipart (file upload)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
